'use strict';

const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const TRIM_KEYS = [
  'DEV_AUTH',
  'DEV_AUTH_SECRET',
  'DEV_ADMIN_EMAIL',
  'DEV_ADMIN_PASSWORD',
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_SERVICE_KEY',
  'PUBLIC_SITE_URL',
  'CORS_ORIGINS',
  'REDIS_URL',
  'BOOTSTRAP_ADMIN_EMAILS',
  'INITIAL_ADMIN_EMAIL',
  'CALENDLY_20_MIN',
  'ADMIN_EMAIL',
  'CRON_SECRET',
  'FROM_EMAIL',
  'SKIP_CANONICAL_HOST',
  'RAILWAY_API_TOKEN',
  'RAILWAY_TEAM_ID',
  'RAILWAY_UP_TIMEOUT_MS',
  'CUSTOMSITE_PLATFORM_HOSTS',
  'CUSTOMSITE_DOMAIN_CACHE_MS',
  'CUSTOMSITE_DOMAIN_PROJECT_MAP',
  'CUSTOMSITE_STAGING_SITES_HOST',
  'CUSTOMSITE_VIDEO_ARCHIVE_BUCKET',
  'YT_DLP_PATH',
  'FFMPEG_PATH',
  'VIDEO_ARCHIVE_CHECK_ONLY',
  'VIDEO_ARCHIVE_ROW_LIMIT',
  'VIDEO_ARCHIVE_DOWNLOAD_LIMIT',
  'VIDEO_ARCHIVE_DOWNLOAD_TIMEOUT_MS',
  'VIDEO_ARCHIVE_TMP',
  'VIDEO_ARCHIVE_YT_FORMAT',
  'VIDEO_ARCHIVE_CRON_ENABLED',
  'VIDEO_ARCHIVE_CRON',
  'VIDEO_ARCHIVE_EMAIL_ALERT',
  'VIDEO_ARCHIVE_SYNC_SECRET',
  'VIDEO_ARCHIVE_SEED_PATH',
  'VIDEO_ARCHIVE_LIST_RATELIMIT_MAX',
];

for (const k of TRIM_KEYS) {
  if (process.env[k] !== undefined && process.env[k] !== null) {
    let v = String(process.env[k]);
    v = v.replace(/^\uFEFF/, '').trim();
    process.env[k] = v;
  }
}

module.exports = {};
